### ISSUE TITLE
Bugs with LSTM and GRU cells

### ISSUE THREAD

**Issue by rodart** [LeavesBreathe/Project_RNN_Enhancement#2]
Hi, I still try to run my seq2seq code based on tensorflow seq2seq translate example. I tried to use you lib for multi-gpu computation and got couple new bugs here.

For LSTM cell: 
  File "/home/ubuntu/poebot/luka_poebot/rnn_cell_enhanced.py", line 441, in __call__
    new_c = c * tf.sigmoid(f + self._forget_bias) + tf.sigmoid(i) * tf.tanh(j)
AttributeError: 'BasicLSTMCell' object has no attribute '_forget_bias'

For GRU cell:
  File "/home/ubuntu/poebot/luka_poebot/seq2seq_enhanced.py", line 386, in sequence_loss_by_example
    log_perps /= total_size #one number is produced here! this is equivalent to log_perps = log_perps/total_size
TypeError: unsupported operand type(s) for /=: 'Tensor' and 'Tensor'

**Comment by LeavesBreathe** [comment]
@rodart , they changed their LSTM script so I'll have to update it accordingly . Unfortunately, I do not have time for that, but you can use basiclstm and that should work.

the gru cell should work. it looks like the error is coming from the sequence loss by example. I just tested it and it does work for me. Have you cloned the most recent version?

**Comment by rodart** [comment]
Yeah, now that works with 0.6.0 tensorflow, thanks!
